# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'tty-prompt', '~> 0.23.1'
gem 'colorize', '~> 0.8.1'
gem 'rspec', '~> 3.10'
gem 'rubocop', '~> 1.23'
gem 'artii', '~> 2.1', '>= 2.1.2'